spring:
  config:
    import: 'optional:file:../../.env[.properties]'

  application:
    name: account-service

  datasource:
    url: ${ACCOUNT_DB_URL:jdbc:postgresql://localhost:5433/account_db}
    username: ${ACCOUNT_DB_USERNAME:account_service_user}
    password: ${ACCOUNT_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

app:
  security:
    internal:
      api-key: ${INTERNAL_API_KEY}
    jwt:
      issuer: ${JWT_ISSUER:secure-bank-auth-service}
      audience: ${JWT_AUDIENCE:secure-bank-api}
      public-key-location: ${ACCOUNT_JWT_PUBLIC_KEY_LOCATION:file:../auth-service/secrets/jwt-public.pem}
